import therapiesIndexJson from "@/data/therapies-index.json";
import { rankTherapyCandidates } from "@/lib/therapy-ranking";

// Server-side therapy catalogue. Backed by src/data/therapies-index.json — a trimmed,
// rankable projection of the ~2.5 MB public Therapy Compass dataset (regenerated by
// scripts/build-therapies-index.mjs). The interactive tool screens still fetch the full
// dataset client-side via src/components/therapy-compass/data/use-therapy-data.ts; this
// module exists so routes can resolve a therapy by slug server-side (generateStaticParams /
// notFound / generateMetadata) and so the universal-search "therapies" domain can rank the
// library without shipping the full dataset into the server graph.

export type TherapyIndexRecord = {
  slug: string;
  name: string;
  category: string | null;
  clinicalSummary: string | null;
  bestUsedFor: string | null;
  targetSymptoms: string | null;
  indications: string | null;
  reviewStatus: string;
  patientSheetAvailable: boolean;
  briefInterventionAvailable: boolean;
  tags: string[];
  aliases: string[];
};

export const therapyRecords = therapiesIndexJson as TherapyIndexRecord[];

const bySlug = new Map(therapyRecords.map((record) => [record.slug, record]));

// The whole catalogue is reachable in every environment. Reachability is
// deliberately NOT gated on review status: a record awaiting qualified-clinician
// sign-off is disclosed as such (`therapyNeedsReview` drives the library notice,
// the result-card badge and the record-page badge) rather than hidden. The
// previous production filter removed all 205 records, so every Therapy route and
// every universal-search therapy hit 404'd for real users while working locally.

export function findTherapyRecord(slug: string): TherapyIndexRecord | undefined {
  return bySlug.get(slug);
}

export function therapyRecordExists(slug: string): boolean {
  return bySlug.has(slug);
}

export function therapySlugs(): string[] {
  return therapyRecords.map((record) => record.slug);
}

/** Slugs whose record ships a brief-intervention version (the rest 404 that route). */
export function therapyBriefSlugs(): string[] {
  return therapyRecords.filter((record) => record.briefInterventionAvailable).map((record) => record.slug);
}

/** Slugs whose record ships a patient sheet (the rest 404 that route). */
export function therapySheetSlugs(): string[] {
  return therapyRecords.filter((record) => record.patientSheetAvailable).map((record) => record.slug);
}

/** True when a therapy still awaits qualified-clinician sign-off. */
export function therapyNeedsReview(record: TherapyIndexRecord): boolean {
  return record.reviewStatus !== "reviewed";
}

/** Count of records still awaiting sign-off — drives the library review notice. */
export function therapyNeedsReviewCount(): number {
  return therapyRecords.filter(therapyNeedsReview).length;
}

export type TherapySearchMatch = { record: TherapyIndexRecord; score: number };

/**
 * Rank the therapy library through the shared Therapy scorer. An empty query
 * returns the alphabetical library (stable order) so the universal-search
 * domain can still surface a browse list.
 */
export function searchTherapyRecords(query: string, expansions: readonly string[] = []): TherapySearchMatch[] {
  return rankTherapyCandidates(therapyRecords, query, expansions);
}
