import {
  Activity,
  AlarmClock,
  ArrowLeftRight,
  Award,
  Bell,
  BookOpen,
  CalendarDays,
  CalendarPlus,
  CircleHelp,
  ClipboardList,
  Clock,
  Compass,
  Download,
  FileText,
  Flag,
  Folder,
  Forward,
  Hand,
  Heart,
  History,
  IdCard,
  Inbox,
  Layers,
  LayoutGrid,
  Link2,
  List,
  ListChecks,
  Map,
  NotebookPen,
  PenLine,
  Phone,
  Plus,
  Presentation,
  QrCode,
  Repeat,
  Search,
  Send,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Target,
  Upload,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";

import type { WorkFrameIconName } from "@/lib/work-frame/areas";

/** The frame's icon names, resolved to the app's one icon set (lucide). */
export const workFrameIcons: Readonly<Record<WorkFrameIconName, LucideIcon>> = {
  alarm: AlarmClock,
  award: Award,
  bell: Bell,
  board: Presentation,
  book: BookOpen,
  calendar: CalendarDays,
  "calendar-plus": CalendarPlus,
  card: IdCard,
  "check-list": ListChecks,
  clipboard: ClipboardList,
  clock: Clock,
  compass: Compass,
  download: Download,
  file: FileText,
  flag: Flag,
  folder: Folder,
  grid: LayoutGrid,
  hand: Hand,
  heart: Heart,
  help: CircleHelp,
  history: History,
  inbox: Inbox,
  layers: Layers,
  link: Link2,
  list: List,
  log: NotebookPen,
  map: Map,
  pen: PenLine,
  people: UserRound,
  phone: Phone,
  plus: Plus,
  pulse: Activity,
  qr: QrCode,
  refer: Forward,
  repeat: Repeat,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  star: Star,
  sun: Sun,
  swap: ArrowLeftRight,
  target: Target,
  upload: Upload,
  user: UserRound,
  users: Users,
};
