import { existsSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import formsCatalog from "../data/forms-catalog.json";
import formsContentReview from "../data/forms-content-review.json";
import mhaSections from "../data/mha-2014-sections.json";
import { recordPinState, reviewProblems } from "./lib/clinical-record-review-contract.mjs";
import { loadFormCatalogDetails, officialFormsRegisterUrl } from "../src/lib/form-catalog";

/**
 * forms:review-sheet — regenerates `docs/evidence/forms-operational-guidance-review.md`.
 *
 * Every one of the 54 forms carries operational guidance drafted from the Act and the
 * approved form, and every one is `drafted` in `data/forms-content-review.json` — no
 * clinician has signed any of it off. Sign-off is a reading task, and it was an
 * archaeology task instead: the guidance is spread across a 3000-line catalogue JSON, its
 * stated basis sits in a second file, its governing sections in a third, and the official
 * PDF behind a URL in a fourth.
 *
 * This sheet puts all of it on one line of sight per form, the way
 * `scripts/build-mha-act-sections.mjs --draft` already does for the Act summaries: what
 * the app displays, what it was drafted from, and the link to the approved form to check
 * it against. The clinical owner signs a form off with `npm run clinical:review`, which
 * writes `status`, `reviewedBy`, `reviewedAt` and a `reviewedContentSha256` content pin in
 * `data/forms-content-review.json`. The caveat in the UI drops for that form and stays up
 * for the rest. Each entry shows its pin state, so an edit after sign-off is visible here.
 *
 * Fully offline. Generated, never hand-edited.
 *
 * Flags:
 *   --check   exit 1 if the sheet is stale, or if any signed form's content pin no longer
 *             matches its guidance (edited since sign-off) or its attestation is incomplete
 */

const repoUrl = (relative: string) => fileURLToPath(new URL(`../${relative}`, import.meta.url));
const OUT = "docs/evidence/forms-operational-guidance-review.md";

type ReviewRow = {
  code: string;
  status: string;
  sections: string[];
  contextualSections: string[];
  basis: string;
  reviewedBy: string | null;
  reviewedAt: string | null;
  reviewedContentSha256?: string | null;
};

const PIN_LABEL: Record<string, string> = {
  unsigned: "not signed yet",
  current: "matches the signed guidance",
  stale: "CONTENT CHANGED SINCE SIGN-OFF — needs signing again",
};

function pinLine(review: ReviewRow | undefined) {
  const state = review ? recordPinState(review, "form", { catalog: formsCatalog }) : "unsigned";
  const shortPin =
    state === "unsigned" || !review?.reviewedContentSha256 ? "" : ` (\`${review.reviewedContentSha256.slice(0, 12)}\`)`;
  return [`**Sign-off pin** ${PIN_LABEL[state]}${shortPin}`, ""];
}

/** Sign-off problems in the review register: stale pins, partial or invalid attestations. */
export function formSignOffProblems(): string[] {
  return reviewProblems((formsContentReview as { forms: ReviewRow[] }).forms, "form", { catalog: formsCatalog });
}

const reviewByCode = new Map(
  (formsContentReview as { forms: ReviewRow[] }).forms.map(
    (entry) => [entry.code.trim().toLowerCase(), entry] as const,
  ),
);
const sectionTitle = new Map(
  (mhaSections as { sections: { section: string; title: string }[] }).sections.map(
    (entry) => [entry.section, entry.title] as const,
  ),
);

function field(label: string, value: string | undefined) {
  const text = (value ?? "").trim();
  return text ? [`**${label}**`, "", text, ""] : [];
}

function list(label: string, values: readonly string[] | undefined) {
  if (!values?.length) return [];
  return [`**${label}**`, "", ...values.map((value) => `- ${value.trim()}`), ""];
}

function sectionLine(numbers: string[], label: string) {
  if (!numbers.length) return [];
  const rendered = numbers.map((number) => {
    const title = sectionTitle.get(number);
    return title ? `s ${number} (${title})` : `s ${number}`;
  });
  return [`**${label}** ${rendered.join("; ")}`, ""];
}

export function buildSheet() {
  const details = loadFormCatalogDetails();
  const drafted = details.filter((entry) => entry.contentReviewStatus !== "reviewed").length;

  const lines: string[] = [
    "# WA MHA 2014 forms — operational guidance review sheet",
    "",
    "<!-- Generated by scripts/build-forms-content-review-sheet.ts. Do not hand-edit. -->",
    "",
    `**${drafted} of ${details.length} forms are awaiting clinical review.**`,
    `**${details.length - drafted} of ${details.length} forms have clinician sign-off.**`,
    "",
    "Each entry below is what the Forms mode actually displays for that form, together with",
    "the basis it was drafted from and a link to the approved form. Each reviewed entry",
    "names its clinician reviewer, original review date and content pin. The app labels",
    "only unsigned guidance as awaiting clinical review.",
    "",
    "The clinical owner signs forms off with `npm run clinical:review` (walk mode steps",
    "through the queue one form at a time; see `docs/clinical-sign-off-how-to.md`). It",
    "writes `status`, `reviewedBy`, `reviewedAt` and a content pin for that code in",
    "`data/forms-content-review.json`. The caveat drops for that form and stays up for the",
    "rest, so this can be done a few forms at a time. Never set those fields by hand.",
    "",
    "The walk order is highest consequence first: 3C, 10B, 10E, 11B, 11E, 6C, then the rest",
    "in catalogue order. Those first six are the clocks where a wrong reading changes whether",
    "a person is lawfully detained, restrained or secluded.",
    "",
    "The content pin covers the drafted basis and sections below plus the form's operational",
    "guidance. If any of it is edited after sign-off, the pin line says so and",
    "`npm run check:forms-review-sheet` fails until the form is signed again.",
    "",
    `Official register: <${officialFormsRegisterUrl}>`,
    "",
    "---",
    "",
  ];

  for (const form of details) {
    const review = reviewByCode.get(form.form.trim().toLowerCase());
    const status = form.contentReviewStatus === "reviewed" ? "REVIEWED" : "awaiting clinical review";
    lines.push(`### Form ${form.form} — ${form.name}`, "");
    lines.push(
      `**Status** ${status}` +
        (review?.reviewedBy ? ` by ${review.reviewedBy}` : "") +
        (review?.reviewedAt ? ` on ${review.reviewedAt}` : ""),
      "",
    );
    lines.push(...pinLine(review));
    lines.push(
      `**Availability** ${form.availability}` +
        (form.officialPdfUrl ? ` · [approved form PDF](${form.officialPdfUrl})` : " · no published PDF"),
      "",
    );
    lines.push(...sectionLine(review?.sections ?? [], "Operational sections"));
    lines.push(...sectionLine(review?.contextualSections ?? [], "Contextual sections"));
    lines.push(...field("Purpose", form.purpose));
    lines.push(...field("Made by", form.maker));
    lines.push(...field("When it applies", form.threshold));
    lines.push(...field("Clock", form.clock));
    lines.push(...field("Authorises", form.authorises));
    lines.push(...field("Does not authorise", form.doesNotAuthorise));
    lines.push(...list("Authority boundaries", form.boundaries));
    lines.push(...list("Common traps", form.traps));
    lines.push(...list("Pre-use checks", form.preUseChecks));
    lines.push(...field("Safety pearl", form.safetyPearl));
    lines.push(...field("Filing and copies", form.copies));
    lines.push(...field("Drafted from", review?.basis));
    lines.push("---", "");
  }

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

function main() {
  const sheet = buildSheet();
  const path = repoUrl(OUT);
  if (process.argv.includes("--check")) {
    const problems = formSignOffProblems();
    if (problems.length) {
      console.error(`Form sign-off problems:\n  - ${problems.join("\n  - ")}`);
      process.exit(1);
    }
    const current = readFileSync(path, "utf8");
    if (current !== sheet) {
      console.error(`${OUT} is stale. Run: npm run forms:review-sheet`);
      process.exit(1);
    }
    console.log(`${OUT} is current.`);
    return;
  }
  writeFileSync(path, sheet);
  console.log(`Wrote ${OUT}.`);
}

const invokedPath = process.argv[1]
  ? pathToFileURL(existsSync(process.argv[1]) ? realpathSync(resolve(process.argv[1])) : resolve(process.argv[1])).href
  : null;
if (invokedPath === import.meta.url) main();
