// Generated by scripts/build-therapies-index.mjs. Do not edit.
export const THERAPY_CATALOGUE_ASSETS = {
  full: "therapies.dbb0c943f5db7dea.json",
  index: "therapies-index.862e5cd7eeae99a5.json",
} as const;

// The generation this one replaced. Retained on disk across one content-
// changing regeneration so a client whose bundle still names the previous
// content-addressed URL does not 404 mid-session; older generations are
// pruned. `useTherapyData` also falls back to the unversioned alias for
// bundles that include that fallback (pre-fallback clients are best-effort).
export const THERAPY_CATALOGUE_ASSETS_PREVIOUS = {
  full: "therapies.62b76a9d2ecf4ed3.json",
  index: "therapies-index.3c76b7eccd22d9b5.json",
} as const;

// First-paint metadata for the Therapy home. The landing page renders only
// the catalogue count and trusted default artifact destinations, so it must
// not download and parse a record projection before its LCP can paint.
export const THERAPY_CATALOGUE_SUMMARY = {
  totalCount: 205,
  needsReviewCount: 47,
  defaultBriefSlug: "applied-relaxation-relaxation-based-therapy",
  defaultSheetSlug: "acceptance-and-commitment-therapy-act",
} as const;
